Repository informalsystems/modelator, pull requests merged in 2022-08, with the labels that each got.

#240 Sanitize ITF parsing
  modelator/pytest/decorators.py
  pyproject.toml
Labels: enhancement

#245 Fix loading the model from .tla file
  modelator/cli/__init__.py
Labels: bug

#257 Fix argument to config file
  modelator/Model.py
  modelator/checker/check.py
  modelator/const_values.py
  modelator/utils/apalache_helpers.py
  modelator/utils/modelator_helpers.py
  modelator/utils/tla_helpers.py
Labels: bug

#229 Refactor tests
  modelator/typecheck.py
  tests/test_model_check.py
  tests/test_model_parse.py
  tests/test_model_parse_file.py
  tests/test_model_typecheck.py
  tests/test_parse.py
  tests/test_typecheck.py
Labels: tests, refactor

#258 Confirm when downloading existing Apalache jar file
  modelator/cli/__init__.py
Labels: cli

#261 Add timestamp to `traces_dir` when checking and sampling
  modelator/cli/__init__.py
  tests/cli/model/Test3.tla
  tests/cli/test_sample.md
  tests/cli/traces_last_generated.sh
  tests/cli/traces_length.sh
  tests/cli/traces_num_generated.sh
Labels: bug, tests, cli

#263 Add version CLI command
  modelator/__init__.py
  modelator/_version.py
  modelator/cli/__init__.py
  tests/test_modelator.py
  tests/test_release.py
Labels: cli

#265 Handle apalache errors when parsing and type checking
  modelator/Model.py
  modelator/ModelShell.py
  modelator/cli/__init__.py
  modelator/exp.py
  modelator/exp_shell.py
  modelator/parse.py
  modelator/typecheck.py
  tests/cli/model/errors/TestError1.tla
  tests/cli/model/errors/TestError2.tla
  tests/cli/test_parse.md
  tests/cli/test_sample.md
  tests/cli/test_typecheck.md
  tests/test_model_parse.py
Labels: bug

#254 Fix multiple errors in uninitialized constants, TLA+ config file, when checking multiple invariants
  modelator/Model.py
  modelator/ModelResult.py
  modelator/checker/CheckResult.py
  modelator/checker/check.py
  modelator/cli/__init__.py
  modelator/monitors/html_monitor.py
  modelator/monitors/markdown_monitor.py
  modelator/utils/ErrorMessage.py
  modelator/utils/modelator_helpers.py
  tests/cli/model/Test1.tla
  tests/cli/run-tests.sh
  tests/cli/test_basic.md
  tests/cli/test_check.md
  tests/cli/test_constants.md
  tests/cli/test_extra_args.md
  tests/cli/test_load_with_config.md
  tests/cli/test_load_without_config.md
  tests/cli/test_sample.md
  tests/cli/trace_check.sh
  tests/cli/traces_last_generated.sh
  tests/cli/traces_length.sh
  tests/cli/traces_num_generated.sh
  tests/test_model_check.py
Labels: bug
