Repository informalsystems/modelator, pull requests merged in 2022-11, with the labels that each got.

#286 Support unknown Apalache versions
  .github/workflows/cli.yml
  .github/workflows/python.yml
  modelator/cli/__init__.py
  modelator/const_values.py
  modelator/utils/apalache_jar.py
  pyproject.toml
Labels: bug, enhancement

#288 Terminology: examples into tests
  modelator/Model.py
  modelator/checker/simulate.py
  modelator/cli/__init__.py
  modelator/cli/model_config_file.py
  modelator/monitors/html_monitor.py
  modelator/monitors/markdown_monitor.py
  modelator/samples/HelloFull.config.toml
  modelator/utils/apalache_helpers.py
  tests/cli/model/Test1.config.toml
  tests/cli/simulation_traces_num_generated.sh
  tests/cli/test_load_with_config.md
  tests/cli/test_sample.md
  tests/cli/traces_num_generated.sh
Labels: enhancement

#290 modelator tutorial
  examples/hanoi/README.md
  examples/hanoi/hanoi/__init__.py
  examples/hanoi/model/hanoi.tla
  examples/hanoi/pyproject.toml
  examples/hanoi/tests/test_hanoi.py
Labels: user support

#298 Updated readme
  INSTALLATION.md
  README.md
  docs/images/modelator_cli.png
Labels: user support
